#import "Image.h"

enum
{
	ANIM_PLAYER_IDLE_RIGHT = 0,
	ANIM_PLAYER_RUN_RIGHT = 1,
	ANIM_PLAYER_JUMP_RIGHT = 2,
	ANIM_PLAYER_FALL_RIGHT = 3,
	ANIM_PLAYER_IDLE_LEFT = 4,
	ANIM_PLAYER_RUN_LEFT = 5,
	ANIM_PLAYER_JUMP_LEFT = 6,
	ANIM_PLAYER_FALL_LEFT = 7,
	ANIM_PLAYER_DANCE = 8
};

enum
{
	ANIM_LOOPING = 0,
	ANIM_ONESHOT = 1
};

enum
{
	ANIM_GRASS = 0,
	ANIM_METAL = 1,
	ANIM_GOAL = 3,
	ANIM_BOMB = 4,
	ANIM_BOMB_ACTION = 5,
	ANIM_LEFT_PLATFORM = 6,
	ANIM_RIGHT_PLATFORM = 7,
	ANIM_UP_PLATFORM = 8,
	ANIM_DOWN_PLATFORM = 9,
	ANIM_FIRE = 10,
	ANIM_GREEN_PORTAL = 11,
	ANIM_GREEN_PORTAL_ACTION = 12,
	ANIM_RED_PORTAL = 13,
	ANIM_RED_PORTAL_ACTION = 14,
	ANIM_BLUE_PORTAL = 15,
	ANIM_BLUE_PORTAL_ACTION = 16,
	ANIM_RIGHT_CONVEYOR = 17,
	ANIM_LEFT_CONVEYOR = 18,
	ANIM_SPRINGBOARD = 19,
	ANIM_SPRINGBOARD_ACTION = 20,
	ANIM_INVISIBLE = 21,
	ANIM_BLADE_BLOCK = 22,
	ANIM_BLADE = 23,
	ANIM_LASER_BLOCK = 24,
	ANIM_GUN_IDLE = 25,
	ANIM_GUN_SHOOT_UP = 26,
	ANIM_GUN_SHOOT_RIGHT = 27,
	ANIM_GUN_SHOOT_DOWN = 28,
	ANIM_GUN_SHOOT_LEFT = 29,
	ANIM_GUN_SHOOT_ALL = 30,
	ANIM_SPIKES_IDLE = 31,
	ANIM_SPIKES_EXTEND_UP = 32,
	ANIM_SPIKES_RETRACT_UP = 33,
	ANIM_SPIKES_EXTEND_RIGHT = 34,
	ANIM_SPIKES_RETRACT_RIGHT = 35,
	ANIM_SPIKES_EXTEND_DOWN = 36,
	ANIM_SPIKES_RETRACT_DOWN = 37,
	ANIM_SPIKES_EXTEND_LEFT = 38,
	ANIM_SPIKES_RETRACT_LEFT = 39,
	ANIM_SPIKES_EXTEND_ALL = 40,
	ANIM_SPIKES_RETRACT_ALL = 41,
	ANIM_LAVA = 42,
	ANIM_EXPLOSION = 43,
	ANIM_LASER_START_RIGHT = 44,
	ANIM_LASER_END_RIGHT = 45,
	ANIM_LASER_START_LEFT = 46,
	ANIM_LASER_END_LEFT = 47,
	ANIM_LASER_START_DOWN = 48,
	ANIM_LASER_END_DOWN = 49,
	ANIM_LASER_START_UP = 50,
	ANIM_LASER_END_UP = 51,
	ANIM_LASER_HORIZONTAL = 52,
	ANIM_LASER_VERTICAL = 53,
	ANIM_FIRE_ACTION = 54,
	ANIM_INVISIBLE_ACTION = 55,
	ANIM_SPIKES_UP = 56,
	ANIM_SPIKES_RIGHT = 57,
	ANIM_SPIKES_DOWN = 58,
	ANIM_SPIKES_LEFT = 59,
	ANIM_SPIKES_ALL = 60,
	ANIM_CHECKPOINT = 61,
	ANIM_CHECKPOINT_ACTION = 62,
	ANIM_GREENSWITCH_OFF = 63,
	ANIM_GREENSWITCH_ON = 64,
	ANIM_GREENBLOCK_VISIBLE = 65,
	ANIM_GREENBLOCK_INVISIBLE = 66,
	ANIM_REDSWITCH_OFF = 67,
	ANIM_REDSWITCH_ON = 68,
	ANIM_REDBLOCK_VISIBLE = 69,
	ANIM_REDBLOCK_INVISIBLE = 70,
	ANIM_BLUESWITCH_OFF = 71,
	ANIM_BLUESWITCH_ON = 72,
	ANIM_BLUEBLOCK_VISIBLE = 73,
	ANIM_BLUEBLOCK_INVISIBLE = 74,
	ANIM_BUBBLE = 75,
	ANIM_BUBBLE_POP = 76,
	ANIM_ICE = 77,
	ANIM_ICE_MELT = 78,
	ANIM_CRYSTAL = 79,
	ANIM_CRYSTAL_BREAK = 80,
	ANIM_SPIKE_BLOCK_UP = 81,
	ANIM_SPIKE_BLOCK_RIGHT = 82,
	ANIM_SPIKE_BLOCK_DOWN = 83,
	ANIM_SPIKE_BLOCK_LEFT = 84,
	ANIM_BUBBLE_WAITING = 85,
	ANIM_CAKE = 86,
};

enum
{
	ANIM_LEFT_BUTTON_UP = 0,
	ANIM_LEFT_BUTTON_DOWN = 1,
	ANIM_RIGHT_BUTTON_UP = 2,
	ANIM_RIGHT_BUTTON_DOWN = 3,
	ANIM_UP_BUTTON_UP = 4,
	ANIM_UP_BUTTON_DOWN = 5,
	ANIM_DOWN_BUTTON_UP = 6,
	ANIM_DOWN_BUTTON_DOWN = 7,
	ANIM_BLOCK_BUTTON = 8,
	ANIM_OK_BUTTON = 9,
	ANIM_RESET_BUTTON = 10,
	ANIM_DESTRUCT_BUTTON = 11,
	ANIM_MENU_BUTTON = 12,
};

enum
{
	ANIM_BULLET_LEFT,
	ANIM_BULLET_RIGHT,
	ANIM_BULLET_UP,
	ANIM_BULLET_DOWN,
};

enum
{
	ANIM_FIREWORK_EXPLODE,
	ANIM_FIREWORK_UP,
};

enum
{
	ANIM_CONGRATS,
};

enum
{
	ANIM_EFFECT_POOF,
	ANIM_EFFECT_BODY_PART_1,
	ANIM_EFFECT_BODY_PART_2,
	ANIM_EFFECT_BODY_PART_3,
	ANIM_EFFECT_BODY_PART_4,
	ANIM_EFFECT_BODY_PART_5,
	ANIM_EFFECT_BODY_PART_6,
	ANIM_EFFECT_BODY_PART_7,
	ANIM_EFFECT_BODY_PART_8,
};

@interface Animation : NSObject

@property(nonatomic, assign)NSMutableArray *framePairs;
@property(nonatomic, assign)NSMutableArray *animBounds;
@property(nonatomic, assign)NSMutableArray *frameList;
@property(nonatomic)NSInteger type;
@property(nonatomic)NSInteger loopType;

- (id)initWithData:(int *)data OfLength:(int)length;

@end
